[AVI-54] Add delete function for configs
gt-space/luna pull request #14
Opened 2024-10-15 16:55 UTC by rzhao310

2024-10-16 23:48 UTC, vink246 commented
Mostly looks good, but a couple of changes:

When clicking delete the state of the button changes to the confirm option, which is great. The problem is if I don't want to confirm there's no way to leave the confirm state unless I reload the page which is annoying. If you could go back to the delete state when the user clicks elsewhere on the screen that would be good. 

Also please add responses to the bot messages previously sent about docuemtnation links, verification evidence, and regression testing. We need to write tests for the GUI in the future. I'll give it a pass for this feature since it's immediately required but at least explain what manual testing you have done to ensure it works.

For future references, all commits should also be preceded with the ticket ID.

Good work!

2024-10-17 01:38 UTC, vink246 requested changes
See previous comment for requested changes

2024-10-17 07:27 UTC, rzhao310 commented
> ### 🚀 Verification Evidence 🚀
> How do you know that your changes work? Reply to this comment with with specific evidence that all functionality added or changed in this pull request is working as expected.

This PR adds the functionality for deleting configs. 

Manual testing was done to ensure functionality of the "Delete" button for deleting configurations:

- Inside the config view, the delete button is positioned intuitively alongside the "Edit" and "Exit" buttons, where the initial state of the button displays "Delete". 
- Clicking on the button for the first time changes the text to "Confirm" without deleting the selected config even when the page is refreshed. 
- Clicking on the button for the second time deletes the config and refreshes the page immediately, causing the config to disappear from the available configurations as it should, also changing the save button's state to "Deleted!" temporarily.
- Clicking on the button for the first time, then clicking anywhere on the page outside of the delete button causes the button to switch back to its default state displaying "delete".
- Console log statements were used to verify the contents and length of the Configurations array before and after deletion of a config. Each time a config is deleted, the config is no longer inside the Configurations array after deletion and the size of the array is also decremented as it should.
- While creating the delete functionality, an edge case was found when attempting to delete the last configuration in the array. To handle this, the index for the DisplayConfigView function was manually decremented and console log statements were used to verify the corrected indices and the edge case was handled


P.S wasn't really sure exactly how to answer this question, so hopefully this suffices. But let me know if it's too vague or just not correct, thanks!

2025-02-20 04:29 UTC, panyab approved these changes
functionality works and looks clean

2025-02-20 04:42 UTC, vink246 approved these changes
Works!

2025-02-20 04:43 UTC, merged